interface Window {
  env: {
    NEXT_PUBLIC_BACKEND_URL: string;
    NEXT_PUBLIC_COGNITO_CALLBACK_URL: string;
    NEXT_PUBLIC_COGNITO_LOGOUT_URL: string;
    NEXT_PUBLIC_AWS_REGION: string;
    NEXT_PUBLIC_COGNITO_DOMAIN: string;
    NEXT_PUBLIC_COGNITO_CLIENT_ID: string;
  };
}